#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := self_balancing_with_line_following

include $(IDF_PATH)/make/project.mk

