#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := hello-world

include C:/Users/dhruva/Desktop/esp/esp-idf/make/project.mk

